name: build_test_clang-tidy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Build and Run Tests
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          submodules: recursive
      
      - name: Install Clang-Tidy
        run: sudo apt-get update && sudo apt-get install -y clang-tidy

      - name: Build and run tests
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ctest --output-on-failure
          find ../ \( -name '*.cpp' -o -name '*.h' \) \
          -not \( -path '*/build/*' -o -path '*/thirdparty/*' \) \
          -exec clang-tidy -p=. --config-file=../.clang-tidy -extra-arg=-Wunused-variable {} + \
          -print | grep "warning" && exit 1 || exit 0

