name: build_test_clang-tidy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Build and Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
            submodules: recursive
      
      - name: Initialize and update submodules
        run: |
            git submodule update --init --recursive
            git submodule update --remote

      - name: Print current directory
        run: pwd
      
      - name: List files in current directory
        run: ls -la
    
      - name: List files in submodule directory
        run: ls -la thirdparty/googletest

      - name: Print contents of CMakeLists.txt
        run: cat CMakeLists.txt

      - name: Install dependencies
        run: sudo apt-get install cmake

      - name: Build and run tests
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ctest --output-on-failure
      
      - name: Install Clang-Tidy
        run: sudo apt-get update && sudo apt-get install -y clang-tidy  
    
      - name: Install g++
        run: sudo apt-get update && sudo apt-get install -y g++


      - name: Generate compilation database with CMake
        run: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -S . -B build

      - name: Run clang-tidy
        run: |
          cd build
          find ../tests ../snakesrc -type f \( -name "*.cpp" -o -name "*.h" \) \
            -exec clang-tidy {} + 
