name: Clang-Tidy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clang_tidy:
    name: Run Clang-Tidy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          submodules: recursive
    
      - name: Initialize and update submodules
        run: |
          git submodule update --init --recursive
          git submodule update --remote

      - name: Install Clang-Tidy
        run: sudo apt-get update && sudo apt-get install -y clang-tidy

      - name: Run Clang-Tidy
        run: |
          mkdir build
          cd build
          cmake ..
          cd ..
          find . -type f \( -path "./tests/*.cpp" -o -path "./snakesrc/*.cpp" -o -path "./snakesrc/*.h" \) -exec clang-tidy {} +
