name: Clang-Tidy on Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clang_tidy:
    name: Run Clang-Tidy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install Clang-Tidy
        run: sudo apt-get update && sudo apt-get install -y clang-tidy

      - name: Run Clang-Tidy
        run: |
          mkdir build
          cd build
          cmake ..
          make
          clang-tidy ../**/*.cpp ../**/*.h