name: clang format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format_check:
    name: Check Code Formatting
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      
      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install clang-format
      
      - name: Check code formatting
        run: |
          clang-format -style=google -output-replacements-xml helloworld.cpp > clang-format-report.xml
          cat clang-format-report.xml
          grep "<replacement " clang-format-report.xml && exit 1
