name: clang format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format_check:
    name: Check Code Formatting
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      
      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install clang-format
        
      - name: Check code formatting
        run:  find ./ \( -name '*.cpp' -o -name '*.h' \) -not \( -path '*/build/*' -o -path '*/thirdparty/*' \) -exec clang-format -style=Google -output-replacements-xml {} + -print | grep "<replacement " && exit 1 || exit 0
